---
- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
    daemon_reload: true

- name: Crear Tablas
  mysql_db: 
    name: "{{ db_name }}"
    state: import 
    target: /tmp/CreateTables.sql
