---
  - name: Instalar MariaDB y complemento Python
    package:
      name: "{{ packages }}"  
      state: latest
    changed_when: true

  - name: Iniciar mariadb
    systemd:
      name: mariadb
      enabled: yes
      state: started
      
  - name:  Instalar pymysql
    pip: 
      name: pymysql
      state: present
  
  - name: Copiar script para crear Tablas
    copy:
      src: ./files/CreateTables.sql
      dest: /tmp/

  - name: Crear base de datos
    mysql_db:
       login_unix_socket: /var/lib/mysql/mysql.sock
       name: "{{ db_name }}"
       state: present
    notify: Crear Tablas

  - name: Correr alta usuario
    community.mysql.mysql_user:
      name: todo
      password: prueba2022
      host: 192.168.190.128
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Habilitar puertos
    firewalld:
      port: "3306/tcp"
      permanent: yes
      state: enabled
    changed_when: true 
    notify: "Reload firewalld"