---
  - name: Iniciar Tomcat
    systemd:
      name: tomcat
      state: started
      enabled: yes

  - name: Reiniciar Apache2
    systemd:
      name: apache2
      state: restarted

  - name: Iniciar HTTPD
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Reiniciar HTTPD
    systemd:
      name: httpd
      state: restarted