---
  all:
    hosts:
    
    children:
      app:
        hosts:
          ubuntu:
            ansible_host: 192.168.190.128
            ansible_user: sysadmin
      db:
        hosts:
          rocky:
            ansible_host: 192.168.190.129
            ansible_user: sysadmin

  